[package]
name = "custinfluxdb"
version = "0.1.0"
edition = "2021"

[dependencies]
influxdb = { version = "0.7.1", features = ["derive"] }
tokio = {version = "1.0", features = ["full"]}
chrono = {version = "0.4.34"}